#!/bin/sh
#
# git test pre-push hook
#
# To use, store as .git/hooks/pre-push inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

# Pre-push configuration
remote=$1
url=$2
echo >&2 "Try pushing $2 to $1"

TEST="go test ./... -race -cover -failfast"
LINTER="golangci-lint run --config ./.github/linters/.golangci.yml"

# Run test and return if failed
printf "Running go test..."
$TEST
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo >&2 "$TEST"
  echo >&2 "Check code to pass test."
  exit 1
fi

# Run linter and return if failed
printf "Running go linter..."
$LINTER
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo >&2 "$LINTER"
  echo >&2 "Check code to pass linter."
  exit 1
fi

exit 0