#!/bin/sh
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

# Pre-commit configuration

RESULT=$(make check)
printf "执行检查中...\n"

if [ -n "$RESULT" ]; then
  echo >&2 "[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中"
  exit 1
fi

exit 0
