// Code generated by "daox"; DO NOT EDIT.
package appcard

import (
	"github.com/fengjx/daox/v2/sqlbuilder"
	"github.com/fengjx/daox/v2/sqlbuilder/ql"

	"time"
)

const (
	TableName   = "app_card"
	IDField     = "id"
	UserIDField = "user_id"
	NumberField = "number"
	StatusField = "status"
	UtimeField  = "utime"
	CtimeField  = "ctime"
)

var Meta = AppcardMeta{}

// AppCardM 身份证信息表
type AppcardMeta struct {
}

func (m AppcardMeta) TableName() string {
	return TableName
}

func (m AppcardMeta) IsAutoIncrement() bool {
	return true
}

func (m AppcardMeta) PrimaryKey() string {
	return "id"
}

func (m AppcardMeta) Columns() []string {
	return []string{
		"id",
		"user_id",
		"number",
		"status",
		"utime",
		"ctime",
	}
}

func IdIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).In(args...)
}

func IdNotIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).NotIn(args...)
}

func IdEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).EQ(val)
}

func IdNotEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).NotEQ(val)
}

func IdLT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LT(val)
}

func IdLTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LTEQ(val)
}

func IdGT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GT(val)
}

func IdGTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GTEQ(val)
}

func IdLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).Like(val)
}

func IdNotLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).NotLike(val)
}

func IdDesc() sqlbuilder.OrderBy {
	return ql.Desc(IDField)
}

func IdAsc() sqlbuilder.OrderBy {
	return ql.Asc(IDField)
}

func UserIdIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UserIDField).In(args...)
}

func UserIdNotIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UserIDField).NotIn(args...)
}

func UserIdEQ(val int64) sqlbuilder.Column {
	return ql.Col(UserIDField).EQ(val)
}

func UserIdNotEQ(val int64) sqlbuilder.Column {
	return ql.Col(UserIDField).NotEQ(val)
}

func UserIdLT(val int64) sqlbuilder.Column {
	return ql.Col(UserIDField).LT(val)
}

func UserIdLTEQ(val int64) sqlbuilder.Column {
	return ql.Col(UserIDField).LTEQ(val)
}

func UserIdGT(val int64) sqlbuilder.Column {
	return ql.Col(UserIDField).GT(val)
}

func UserIdGTEQ(val int64) sqlbuilder.Column {
	return ql.Col(UserIDField).GTEQ(val)
}

func UserIdLike(val string) sqlbuilder.Column {
	return ql.Col(UserIDField).Like(val)
}

func UserIdNotLike(val string) sqlbuilder.Column {
	return ql.Col(UserIDField).NotLike(val)
}

func UserIdDesc() sqlbuilder.OrderBy {
	return ql.Desc(UserIDField)
}

func UserIdAsc() sqlbuilder.OrderBy {
	return ql.Asc(UserIDField)
}

func NumberIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(NumberField).In(args...)
}

func NumberNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(NumberField).NotIn(args...)
}

func NumberEQ(val string) sqlbuilder.Column {
	return ql.Col(NumberField).EQ(val)
}

func NumberNotEQ(val string) sqlbuilder.Column {
	return ql.Col(NumberField).NotEQ(val)
}

func NumberLT(val string) sqlbuilder.Column {
	return ql.Col(NumberField).LT(val)
}

func NumberLTEQ(val string) sqlbuilder.Column {
	return ql.Col(NumberField).LTEQ(val)
}

func NumberGT(val string) sqlbuilder.Column {
	return ql.Col(NumberField).GT(val)
}

func NumberGTEQ(val string) sqlbuilder.Column {
	return ql.Col(NumberField).GTEQ(val)
}

func NumberLike(val string) sqlbuilder.Column {
	return ql.Col(NumberField).Like(val)
}

func NumberNotLike(val string) sqlbuilder.Column {
	return ql.Col(NumberField).NotLike(val)
}

func NumberDesc() sqlbuilder.OrderBy {
	return ql.Desc(NumberField)
}

func NumberAsc() sqlbuilder.OrderBy {
	return ql.Asc(NumberField)
}

func StatusIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).In(args...)
}

func StatusNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).NotIn(args...)
}

func StatusEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).EQ(val)
}

func StatusNotEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotEQ(val)
}

func StatusLT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LT(val)
}

func StatusLTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LTEQ(val)
}

func StatusGT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GT(val)
}

func StatusGTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GTEQ(val)
}

func StatusLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).Like(val)
}

func StatusNotLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotLike(val)
}

func StatusDesc() sqlbuilder.OrderBy {
	return ql.Desc(StatusField)
}

func StatusAsc() sqlbuilder.OrderBy {
	return ql.Asc(StatusField)
}

func UtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).In(args...)
}

func UtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).NotIn(args...)
}

func UtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).EQ(val)
}

func UtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).NotEQ(val)
}

func UtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LT(val)
}

func UtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LTEQ(val)
}

func UtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GT(val)
}

func UtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GTEQ(val)
}

func UtimeLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).Like(val)
}

func UtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).NotLike(val)
}

func UtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(UtimeField)
}

func UtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(UtimeField)
}

func CtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).In(args...)
}

func CtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).NotIn(args...)
}

func CtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).EQ(val)
}

func CtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).NotEQ(val)
}

func CtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LT(val)
}

func CtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LTEQ(val)
}

func CtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GT(val)
}

func CtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GTEQ(val)
}

func CtimeLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).Like(val)
}

func CtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).NotLike(val)
}

func CtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(CtimeField)
}

func CtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(CtimeField)
}
