// Code generated by "daox"; DO NOT EDIT.
package dao

import (
	"context"
	"github.com/fengjx/daox/v2"
	"github.com/fengjx/daox/v2/example/dao/schema"
)

// Preload 预加载
func (d *orderDao) Preload(paths ...string) *orderDao {
	newDao := new(orderDao)
	*newDao = *d
	newDao.Dao = d.Dao.Preload(paths...)
	return newDao
}

// RelFiller auto-generated relation loader. DO NOT MODIFY.
func (d *orderDao) RelFiller(ctx context.Context, list []*schema.AppOrder, p *daox.PreloadNode) error {
	if len(list) == 0 || p == nil {
		return nil
	}
	d.fillUser(ctx, list, p)
	return nil
}

// fillUser m2o auto-generated relation loader. DO NOT MODIFY.
func (d *orderDao) fillUser(ctx context.Context, list []*schema.AppOrder, p *daox.PreloadNode) error {
	n, ok := p.Node["User"]
	if !ok {
		return nil
	}

	refIDSet := make(map[any]struct{})
	for _, m := range list {
		refIDSet[m.UserID] = struct{}{}
	}
	var ids []any
	for id := range refIDSet {
		ids = append(ids, id)
	}
	var refDao = daox.GetDao[*schema.AppUser]("app_user").WithPreloadNode(n)
	refList, err := refDao.ListByIDsContext(ctx, ids)
	if err != nil {
		return err
	}
	refMap := make(map[any]*schema.AppUser)
	for _, v := range refList {
		refMap[v.ID] = v
	}
	for _, m := range list {
		m.User = refMap[m.UserID]
	}
	return nil
}
