// Code generated by "daox"; DO NOT EDIT.
package dao

import (
	"context"
	"github.com/fengjx/daox/v2"
	"github.com/fengjx/daox/v2/example/dao/schema"
)

// Preload 预加载
func (d *userDao) Preload(paths ...string) *userDao {
	newDao := new(userDao)
	*newDao = *d
	newDao.Dao = d.Dao.Preload(paths...)
	return newDao
}

// RelFiller auto-generated relation loader. DO NOT MODIFY.
func (d *userDao) RelFiller(ctx context.Context, list []*schema.AppUser, p *daox.PreloadNode) error {
	if len(list) == 0 || p == nil {
		return nil
	}
	d.fillCard(ctx, list, p)
	d.fillOrders(ctx, list, p)
	return nil
}

// fillCard o2o auto-generated relation loader. DO NOT MODIFY.
func (d *userDao) fillCard(ctx context.Context, list []*schema.AppUser, p *daox.PreloadNode) error {
	n, ok := p.Node["Card"]
	if !ok {
		return nil
	}

	ids := make([]any, 0, len(list))
	for _, m := range list {
		ids = append(ids, m.ID)
	}
	var refDao = daox.GetDao[*schema.AppCard]("app_card").WithPreloadNode(n)
	refList, err := refDao.ListByIDsContext(ctx, ids)
	if err != nil {
		return err
	}
	refMap := make(map[any]*schema.AppCard)
	for _, v := range refList {
		refMap[v.UserID] = v
	}
	for _, m := range list {
		m.Card = refMap[m.ID]
	}
	return nil
}

// fillOrders o2m auto-generated relation loader. DO NOT MODIFY.
func (d *userDao) fillOrders(ctx context.Context, list []*schema.AppUser, p *daox.PreloadNode) error {
	n, ok := p.Node["Orders"]
	if !ok {
		return nil
	}

	ids := make([]any, 0, len(list))
	for _, m := range list {
		ids = append(ids, m.ID)
	}
	var refDao = daox.GetDao[*schema.AppOrder]("app_order").WithPreloadNode(n)
	refList, err := refDao.ListByIDsContext(ctx, ids)
	if err != nil {
		return err
	}
	refMap := make(map[any][]*schema.AppOrder)
	for _, v := range refList {
		refMap[v.UserID] = append(refMap[v.UserID], v)
	}
	for _, m := range list {
		m.Orders = refMap[m.ID]
	}
	return nil
}
