run:
  timeout: 5m
  skip-files:
    - generated.*
    - gen.*

issues:
  new: true
  exclude-rules:
    - path: _test\.go
      linters:
        - unused

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - rowserrcheck
    - staticcheck
    - unused
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - errname
    - gochecknoglobals
    - sqlclosecheck
#  disable:

linters-settings:
  gci:
    local-prefixes: github.com/fengjx/daox
  goimports:
    local-prefixes: github.com/fengjx/daox
