// Code generated by "daox"; DO NOT EDIT.
package schema

import (
	"time"

	"github.com/fengjx/daox/v2"
)

// AppUser 用户信息表
type AppUser struct {
	ID       int64     `json:"id" db:"id"`             // -
	Username string    `json:"username" db:"username"` // 用户名
	Pwd      string    `json:"pwd" db:"pwd"`           // 密码
	Salt     string    `json:"salt" db:"salt"`         // 密码盐
	Email    string    `json:"email" db:"email"`       // 邮箱
	Nickname string    `json:"nickname" db:"nickname"` // 昵称
	Avatar   string    `json:"avatar" db:"avatar"`     // 头像
	Phone    string    `json:"phone" db:"phone"`       // 手机号
	Status   string    `json:"status" db:"status"`     // 用户状态
	Remark   string    `json:"remark" db:"remark"`     // 备注
	Utime    time.Time `json:"utime" db:"utime"`       // 更新时间
	Ctime    time.Time `json:"ctime" db:"ctime"`       // 创建时间

	// relations
	Card   *AppCard    `json:"card"`
	Orders []*AppOrder `json:"orders"`
}

func (m *AppUser) GetID() any {
	return m.ID
}

func (m *AppUser) New() daox.Model {
	return &AppUser{}
}
