// Code generated by "daox"; DO NOT EDIT.
package schema

import (
	"time"

	"github.com/fengjx/daox/v2"
)

// AppCard 身份证信息表
type AppCard struct {
	ID     int64     `json:"id"`      // -
	UserID int64     `json:"user_id"` // 用户ID
	Number string    `json:"number"`  // 卡号
	Status string    `json:"status"`  // 卡状态
	Utime  time.Time `json:"utime"`   // 更新时间
	Ctime  time.Time `json:"ctime"`   // 创建时间
}

func (m *AppCard) GetID() any {
	return m.ID
}

func (m *AppCard) New() daox.Model {
	return &AppCard{}
}
