// Code generated by "daox"; DO NOT EDIT.
package schema

import (
	"time"

	"github.com/fengjx/daox/v2"
)

// AppOrder 订单信息表
type AppOrder struct {
	ID     int64     `json:"id"`      // -
	UserID int64     `json:"user_id"` // 用户ID
	Amount string    `json:"amount"`  // 订单金额
	Status string    `json:"status"`  // 订单状态
	Remark string    `json:"remark"`  // 备注
	Utime  time.Time `json:"utime"`   // 更新时间
	Ctime  time.Time `json:"ctime"`   // 创建时间
}

func (m *AppOrder) GetID() any {
	return m.ID
}

func (m *AppOrder) New() daox.Model {
	return &AppOrder{}
}
