ds:
  type: mysql
  dsn: root:1234@tcp(192.168.1.200:3306)/gogo
target:
  custom:
    tag-name: db
    out-dir: ./out
    template-dir:
    var:
      a: aa
      b: bb
  tables:
    - user
    - blog
