ds:
  type: mysql
  dsn: root:123456@tcp(192.168.6.121:3306)/lucky
target:
  custom:
    gomod: github.com/fengjx/daox/v2
    tag-name: json
    target-dir: out/dao
    var:
      foo: bar
  tables:
    sys_user:
      short-name: user
    sys_dict:
      target-dir: out/tears/dao
      short-name: dict