ds:
  type: mysql
  dsn: root:1234@tcp(192.168.1.200:3306)/gogo
target:
  custom:
    tag-name: json
    out-dir: ./out
    var:
      foo: bar
  tables:
    user: {module: sys}
    blog: {module: core}
