ds:
  type: mysql
  dsn: root:123456@tcp(192.168.6.121:3306)/demo
target:
  custom:
    gomod: github.com/fengjx/daox/v2
    tag-name: json
    target-dir: out/dao
    var:
      foo: bar
  tables:
    app_user:
      short-name: user
      relations:
        - name: Card
          type: o2o
          table: app_card
          foreign_key: user_id
          ref_key: id
        - name: Orders
          type: o2m
          table: app_order
          foreign_key: user_id
          ref_key: id
    app_order:
      short-name: order
      relations:
        - name: User
          type: m2o
          table: app_user
          foreign_key: id
          ref_key: user_id
    app_card:
      short-name: card
      relations:
        - name: User
          type: o2o
          table: app_user
          foreign_key: id
          ref_key: user_id